/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_h_INCLUDE
#define __map_h_INCLUDE

#define MapWidth 20
#define MapHeight 18
#define MapBank 0

extern const unsigned char Map[];

#endif

/* End of MAP.H */
