/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 6

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tiles_h_INCLUDE
#define __tiles_h_INCLUDE

/* Bank of tiles. */
#define TileBank 0

/* Super Gameboy palette 0 */
#define TileSGBPal0c0 6076
#define TileSGBPal0c1 8935
#define TileSGBPal0c2 6596
#define TileSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TileSGBPal1c0 6076
#define TileSGBPal1c1 8935
#define TileSGBPal1c2 6596
#define TileSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TileSGBPal2c0 6076
#define TileSGBPal2c1 8935
#define TileSGBPal2c2 6596
#define TileSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TileSGBPal3c0 6076
#define TileSGBPal3c1 8935
#define TileSGBPal3c2 6596
#define TileSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TileCGBPal0c0 32733
#define TileCGBPal0c1 31640
#define TileCGBPal0c2 32331
#define TileCGBPal0c3 348

/* Gameboy Color palette 1 */
#define TileCGBPal1c0 32733
#define TileCGBPal1c1 20974
#define TileCGBPal1c2 738
#define TileCGBPal1c3 8289

/* Gameboy Color palette 2 */
#define TileCGBPal2c0 32733
#define TileCGBPal2c1 8935
#define TileCGBPal2c2 6596
#define TileCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TileCGBPal3c0 32733
#define TileCGBPal3c1 31544
#define TileCGBPal3c2 20974
#define TileCGBPal3c3 8289

/* Gameboy Color palette 4 */
#define TileCGBPal4c0 32733
#define TileCGBPal4c1 31640
#define TileCGBPal4c2 32331
#define TileCGBPal4c3 1539

/* Gameboy Color palette 5 */
#define TileCGBPal5c0 32733
#define TileCGBPal5c1 20974
#define TileCGBPal5c2 738
#define TileCGBPal5c3 8289

/* Gameboy Color palette 6 */
#define TileCGBPal6c0 32733
#define TileCGBPal6c1 20974
#define TileCGBPal6c2 738
#define TileCGBPal6c3 8289

/* Gameboy Color palette 7 */
#define TileCGBPal7c0 32733
#define TileCGBPal7c1 20974
#define TileCGBPal7c2 738
#define TileCGBPal7c3 8289
/* CGBpalette entries. */
extern const unsigned char TileCGB[];
/* Start of tile array. */
extern const unsigned char Tile[];
#define TileLen 7

#endif

/* End of TILES.H */
